name: Integration Tests

on:
  push:
    branches:
      - feature/integration-tests
  pull_request:
    branches:
      - feature/integration-tests

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run integration tests
        run: python -m pytest -q static/tests/integration